"""Constants for the Scenario IFSEI."""

IFSEI_ATTR_BRIGHTNESS = "w"
IFSEI_ATTR_AVAILABLE = "available"
IFSEI_ATTR_COMMAND = "command"
IFSEI_ATTR_RED = "r"
IFSEI_ATTR_GREEN = "g"
IFSEI_ATTR_BLUE = "b"
IFSEI_ATTR_SHADERS_UP = "address1"
IFSEI_ATTR_SHADERS_STOP = "address2"
IFSEI_ATTR_SHADERS_DOWN = "address3"

IFSEI_COVER_UP = "up"
IFSEI_COVER_DOWN = "down"
IFSEI_COVER_STOP = "stop"

LIGHT_DEVICES = "lights"
COVER_DEVICES = "covers"
